"""
phy.py - Physical Layer

This module handles the conversion between bits and audio waveforms.
It's the "PHY" layer - the lowest level of our modem.

Key concepts:
- A sine wave is generated by: y(t) = amplitude * sin(2 * pi * frequency * t)
- We sample this continuous function at discrete time intervals (sample_rate)
- The result is an array of numbers that the DAC converts to voltage
"""

import numpy as np

# --- Configuration ---

SAMPLE_RATE = 44100  # Samples per second (CD quality)

# FSK frequencies: we use two tones to represent binary
FREQ_0 = 1000  # Hz - represents a '0' bit
FREQ_1 = 2000  # Hz - represents a '1' bit

# Baud rate: how many bits per second we transmit
# Lower = more reliable (more cycles per bit), but slower
BAUD_RATE = 100  # 100 bits per second = 10ms per bit
BIT_DURATION = 1.0 / BAUD_RATE  # seconds per bit
SAMPLES_PER_BIT = int(SAMPLE_RATE * BIT_DURATION)  # 441 samples


def generate_tone(frequency, duration, sample_rate=SAMPLE_RATE, amplitude=0.5):
    """
    Generate a sine wave at the specified frequency.

    Args:
        frequency: Tone frequency in Hz
        duration: Length in seconds
        sample_rate: Samples per second
        amplitude: Peak amplitude (0.0 to 1.0)

    Returns:
        numpy array of float32 samples
    """
    # Create array of time values: [0, 1/sr, 2/sr, ..., duration]
    num_samples = int(sample_rate * duration)
    t = np.arange(num_samples) / sample_rate

    # Generate sine wave: y = A * sin(2πft)
    wave = amplitude * np.sin(2 * np.pi * frequency * t)

    return wave.astype(np.float32)


def encode_bit(bit):
    """
    Convert a single bit (0 or 1) to its audio waveform.

    Args:
        bit: Integer 0 or 1

    Returns:
        numpy array of samples representing that bit
    """
    frequency = FREQ_1 if bit else FREQ_0
    return generate_tone(frequency, BIT_DURATION)


def encode_byte(byte_value):
    """
    Convert a byte (0-255) to audio waveform.

    Transmits MSB (most significant bit) first.

    Args:
        byte_value: Integer 0-255

    Returns:
        numpy array of samples representing all 8 bits
    """
    waveforms = []

    # Extract bits from MSB to LSB
    for i in range(7, -1, -1):
        bit = (byte_value >> i) & 1
        waveforms.append(encode_bit(bit))

    return np.concatenate(waveforms)


def encode_bytes(data):
    """
    Convert a sequence of bytes to audio waveform.

    Args:
        data: bytes object or list of integers

    Returns:
        numpy array of samples
    """
    waveforms = [encode_byte(b) for b in data]
    return np.concatenate(waveforms)
