# Protocol Constants

# IP Protocol Numbers
PROTO_ICMP = 1
PROTO_TCP = 6
PROTO_UDP = 17

# ICMP Types
ICMP_TYPE_ECHO_REPLY = 0
ICMP_TYPE_ECHO_REQUEST = 8

# TCP Flags
TCP_FLAG_FIN = 0x01
TCP_FLAG_SYN = 0x02
TCP_FLAG_RST = 0x04
TCP_FLAG_PSH = 0x08
TCP_FLAG_ACK = 0x10
TCP_FLAG_URG = 0x20
TCP_FLAG_ECE = 0x40
TCP_FLAG_CWR = 0x80
TCP_FLAG_NS = 0x100
